[package]
name = "femme"
version = "1.0.0"
authors = ["lrlna <shestak.irina@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.7", features = ["kv_unstable"] }
async-log = "1.1.0"
console = "0.7.7"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
